/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateContactInfoDto
 */
export interface CreateContactInfoDto {
    /**
     * ContactInfo Type
     * @type {string}
     * @memberof CreateContactInfoDto
     */
    typeCd: CreateContactInfoDtoTypeCdEnum;
    /**
     * ContactInfo Value
     * @type {string}
     * @memberof CreateContactInfoDto
     */
    value: string;
    /**
     * Is Primary ContactInfo
     * @type {boolean}
     * @memberof CreateContactInfoDto
     */
    isPrimary: boolean;
}


/**
 * @export
 */
export const CreateContactInfoDtoTypeCdEnum = {
    Email: 'email',
    Phone: 'phone'
} as const;
export type CreateContactInfoDtoTypeCdEnum = typeof CreateContactInfoDtoTypeCdEnum[keyof typeof CreateContactInfoDtoTypeCdEnum];


/**
 * Check if a given object implements the CreateContactInfoDto interface.
 */
export function instanceOfCreateContactInfoDto(value: object): value is CreateContactInfoDto {
    if (!('typeCd' in value) || value['typeCd'] === undefined) return false;
    if (!('value' in value) || value['value'] === undefined) return false;
    if (!('isPrimary' in value) || value['isPrimary'] === undefined) return false;
    return true;
}

export function CreateContactInfoDtoFromJSON(json: any): CreateContactInfoDto {
    return CreateContactInfoDtoFromJSONTyped(json, false);
}

export function CreateContactInfoDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateContactInfoDto {
    if (json == null) {
        return json;
    }
    return {
        
        'typeCd': json['typeCd'],
        'value': json['value'],
        'isPrimary': json['isPrimary'],
    };
}

export function CreateContactInfoDtoToJSON(json: any): CreateContactInfoDto {
    return CreateContactInfoDtoToJSONTyped(json, false);
}

export function CreateContactInfoDtoToJSONTyped(value?: CreateContactInfoDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'typeCd': value['typeCd'],
        'value': value['value'],
        'isPrimary': value['isPrimary'],
    };
}

