/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateLeadDto } from './CreateLeadDto';
import {
    CreateLeadDtoFromJSON,
    CreateLeadDtoFromJSONTyped,
    CreateLeadDtoToJSON,
    CreateLeadDtoToJSONTyped,
} from './CreateLeadDto';

/**
 * 
 * @export
 * @interface CreateLeadRequestDto
 */
export interface CreateLeadRequestDto {
    /**
     * Lead
     * @type {CreateLeadDto}
     * @memberof CreateLeadRequestDto
     */
    lead: CreateLeadDto;
}

/**
 * Check if a given object implements the CreateLeadRequestDto interface.
 */
export function instanceOfCreateLeadRequestDto(value: object): value is CreateLeadRequestDto {
    if (!('lead' in value) || value['lead'] === undefined) return false;
    return true;
}

export function CreateLeadRequestDtoFromJSON(json: any): CreateLeadRequestDto {
    return CreateLeadRequestDtoFromJSONTyped(json, false);
}

export function CreateLeadRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateLeadRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lead': CreateLeadDtoFromJSON(json['lead']),
    };
}

export function CreateLeadRequestDtoToJSON(json: any): CreateLeadRequestDto {
    return CreateLeadRequestDtoToJSONTyped(json, false);
}

export function CreateLeadRequestDtoToJSONTyped(value?: CreateLeadRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lead': CreateLeadDtoToJSON(value['lead']),
    };
}

