/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetadataResponseDto } from './MetadataResponseDto';
import {
    MetadataResponseDtoFromJSON,
    MetadataResponseDtoFromJSONTyped,
    MetadataResponseDtoToJSON,
    MetadataResponseDtoToJSONTyped,
} from './MetadataResponseDto';

/**
 * 
 * @export
 * @interface DataMetadataResponseDto
 */
export interface DataMetadataResponseDto {
    /**
     * Metadata info
     * @type {MetadataResponseDto}
     * @memberof DataMetadataResponseDto
     */
    metadata: MetadataResponseDto;
}

/**
 * Check if a given object implements the DataMetadataResponseDto interface.
 */
export function instanceOfDataMetadataResponseDto(value: object): value is DataMetadataResponseDto {
    if (!('metadata' in value) || value['metadata'] === undefined) return false;
    return true;
}

export function DataMetadataResponseDtoFromJSON(json: any): DataMetadataResponseDto {
    return DataMetadataResponseDtoFromJSONTyped(json, false);
}

export function DataMetadataResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataMetadataResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'metadata': MetadataResponseDtoFromJSON(json['metadata']),
    };
}

export function DataMetadataResponseDtoToJSON(json: any): DataMetadataResponseDto {
    return DataMetadataResponseDtoToJSONTyped(json, false);
}

export function DataMetadataResponseDtoToJSONTyped(value?: DataMetadataResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadata': MetadataResponseDtoToJSON(value['metadata']),
    };
}

