/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SortingDto } from './SortingDto';
import {
    SortingDtoFromJSON,
    SortingDtoFromJSONTyped,
    SortingDtoToJSON,
    SortingDtoToJSONTyped,
} from './SortingDto';
import type { OffsetPaginationDto } from './OffsetPaginationDto';
import {
    OffsetPaginationDtoFromJSON,
    OffsetPaginationDtoFromJSONTyped,
    OffsetPaginationDtoToJSON,
    OffsetPaginationDtoToJSONTyped,
} from './OffsetPaginationDto';

/**
 * 
 * @export
 * @interface MetadataResponseDto
 */
export interface MetadataResponseDto {
    /**
     * Offset pagination info
     * @type {OffsetPaginationDto}
     * @memberof MetadataResponseDto
     */
    pagination?: OffsetPaginationDto;
    /**
     * Sorting info
     * @type {SortingDto}
     * @memberof MetadataResponseDto
     */
    sort?: SortingDto;
    /**
     * Filter info
     * @type {object}
     * @memberof MetadataResponseDto
     */
    filter?: object;
    /**
     * Projection fields
     * @type {Array<string>}
     * @memberof MetadataResponseDto
     */
    projection?: Array<string>;
}

/**
 * Check if a given object implements the MetadataResponseDto interface.
 */
export function instanceOfMetadataResponseDto(value: object): value is MetadataResponseDto {
    return true;
}

export function MetadataResponseDtoFromJSON(json: any): MetadataResponseDto {
    return MetadataResponseDtoFromJSONTyped(json, false);
}

export function MetadataResponseDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataResponseDto {
    if (json == null) {
        return json;
    }
    return {
        
        'pagination': json['pagination'] == null ? undefined : OffsetPaginationDtoFromJSON(json['pagination']),
        'sort': json['sort'] == null ? undefined : SortingDtoFromJSON(json['sort']),
        'filter': json['filter'] == null ? undefined : json['filter'],
        'projection': json['projection'] == null ? undefined : json['projection'],
    };
}

export function MetadataResponseDtoToJSON(json: any): MetadataResponseDto {
    return MetadataResponseDtoToJSONTyped(json, false);
}

export function MetadataResponseDtoToJSONTyped(value?: MetadataResponseDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'pagination': OffsetPaginationDtoToJSON(value['pagination']),
        'sort': SortingDtoToJSON(value['sort']),
        'filter': value['filter'],
        'projection': value['projection'],
    };
}

