/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OffsetPaginationDto
 */
export interface OffsetPaginationDto {
    /**
     * Pagination offset
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    offset: number;
    /**
     * Pagination limit
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    limit: number;
    /**
     * Total records
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    count?: number;
}

/**
 * Check if a given object implements the OffsetPaginationDto interface.
 */
export function instanceOfOffsetPaginationDto(value: object): value is OffsetPaginationDto {
    if (!('offset' in value) || value['offset'] === undefined) return false;
    if (!('limit' in value) || value['limit'] === undefined) return false;
    return true;
}

export function OffsetPaginationDtoFromJSON(json: any): OffsetPaginationDto {
    return OffsetPaginationDtoFromJSONTyped(json, false);
}

export function OffsetPaginationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): OffsetPaginationDto {
    if (json == null) {
        return json;
    }
    return {
        
        'offset': json['offset'],
        'limit': json['limit'],
        'count': json['count'] == null ? undefined : json['count'],
    };
}

export function OffsetPaginationDtoToJSON(json: any): OffsetPaginationDto {
    return OffsetPaginationDtoToJSONTyped(json, false);
}

export function OffsetPaginationDtoToJSONTyped(value?: OffsetPaginationDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'offset': value['offset'],
        'limit': value['limit'],
        'count': value['count'],
    };
}

