/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CreateContactInfoDto } from './CreateContactInfoDto';
import {
    CreateContactInfoDtoFromJSON,
    CreateContactInfoDtoFromJSONTyped,
    CreateContactInfoDtoToJSON,
    CreateContactInfoDtoToJSONTyped,
} from './CreateContactInfoDto';

/**
 * 
 * @export
 * @interface PatchLeadDto
 */
export interface PatchLeadDto {
    /**
     * Lead First Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    firstName: string;
    /**
     * Lead Second Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    secondName?: string;
    /**
     * Lead Last Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    lastName: string;
    /**
     * Lead Second Last Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    secondLastName?: string;
    /**
     * Represents Organization
     * @type {boolean}
     * @memberof PatchLeadDto
     */
    representsOrganization: boolean;
    /**
     * Lead Organization Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    organizationName?: string;
    /**
     * Lead Job Title
     * @type {string}
     * @memberof PatchLeadDto
     */
    jobTitle?: string;
    /**
     * Lead Contact Information
     * @type {Array<CreateContactInfoDto>}
     * @memberof PatchLeadDto
     */
    contactData: Array<CreateContactInfoDto>;
    /**
     * Lead Source Code
     * @type {string}
     * @memberof PatchLeadDto
     */
    sourceCd: PatchLeadDtoSourceCdEnum;
    /**
     * Assigned To
     * @type {string}
     * @memberof PatchLeadDto
     */
    assignedTo?: string;
    /**
     * Assigned DateTime
     * @type {Date}
     * @memberof PatchLeadDto
     */
    assignedAt?: Date;
    /**
     * Company Id
     * @type {string}
     * @memberof PatchLeadDto
     */
    companyId: string;
}


/**
 * @export
 */
export const PatchLeadDtoSourceCdEnum = {
    Marketplace: 'marketplace',
    Website: 'website',
    Email: 'email',
    Phone: 'phone',
    Facebook: 'facebook',
    Instagram: 'instagram',
    Twitter: 'twitter',
    Linkedin: 'linkedin',
    Youtube: 'youtube',
    Google: 'google',
    Other: 'other'
} as const;
export type PatchLeadDtoSourceCdEnum = typeof PatchLeadDtoSourceCdEnum[keyof typeof PatchLeadDtoSourceCdEnum];


/**
 * Check if a given object implements the PatchLeadDto interface.
 */
export function instanceOfPatchLeadDto(value: object): value is PatchLeadDto {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('representsOrganization' in value) || value['representsOrganization'] === undefined) return false;
    if (!('contactData' in value) || value['contactData'] === undefined) return false;
    if (!('sourceCd' in value) || value['sourceCd'] === undefined) return false;
    if (!('companyId' in value) || value['companyId'] === undefined) return false;
    return true;
}

export function PatchLeadDtoFromJSON(json: any): PatchLeadDto {
    return PatchLeadDtoFromJSONTyped(json, false);
}

export function PatchLeadDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchLeadDto {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['firstName'],
        'secondName': json['secondName'] == null ? undefined : json['secondName'],
        'lastName': json['lastName'],
        'secondLastName': json['secondLastName'] == null ? undefined : json['secondLastName'],
        'representsOrganization': json['representsOrganization'],
        'organizationName': json['organizationName'] == null ? undefined : json['organizationName'],
        'jobTitle': json['jobTitle'] == null ? undefined : json['jobTitle'],
        'contactData': ((json['contactData'] as Array<any>).map(CreateContactInfoDtoFromJSON)),
        'sourceCd': json['sourceCd'],
        'assignedTo': json['assignedTo'] == null ? undefined : json['assignedTo'],
        'assignedAt': json['assignedAt'] == null ? undefined : (new Date(json['assignedAt'])),
        'companyId': json['companyId'],
    };
}

export function PatchLeadDtoToJSON(json: any): PatchLeadDto {
    return PatchLeadDtoToJSONTyped(json, false);
}

export function PatchLeadDtoToJSONTyped(value?: PatchLeadDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'firstName': value['firstName'],
        'secondName': value['secondName'],
        'lastName': value['lastName'],
        'secondLastName': value['secondLastName'],
        'representsOrganization': value['representsOrganization'],
        'organizationName': value['organizationName'],
        'jobTitle': value['jobTitle'],
        'contactData': ((value['contactData'] as Array<any>).map(CreateContactInfoDtoToJSON)),
        'sourceCd': value['sourceCd'],
        'assignedTo': value['assignedTo'],
        'assignedAt': value['assignedAt'] == null ? undefined : ((value['assignedAt']).toISOString()),
        'companyId': value['companyId'],
    };
}

