/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PatchLeadDto } from './PatchLeadDto';
import {
    PatchLeadDtoFromJSON,
    PatchLeadDtoFromJSONTyped,
    PatchLeadDtoToJSON,
    PatchLeadDtoToJSONTyped,
} from './PatchLeadDto';

/**
 * 
 * @export
 * @interface PatchLeadRequestDto
 */
export interface PatchLeadRequestDto {
    /**
     * Lead
     * @type {PatchLeadDto}
     * @memberof PatchLeadRequestDto
     */
    lead: PatchLeadDto;
}

/**
 * Check if a given object implements the PatchLeadRequestDto interface.
 */
export function instanceOfPatchLeadRequestDto(value: object): value is PatchLeadRequestDto {
    if (!('lead' in value) || value['lead'] === undefined) return false;
    return true;
}

export function PatchLeadRequestDtoFromJSON(json: any): PatchLeadRequestDto {
    return PatchLeadRequestDtoFromJSONTyped(json, false);
}

export function PatchLeadRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchLeadRequestDto {
    if (json == null) {
        return json;
    }
    return {
        
        'lead': PatchLeadDtoFromJSON(json['lead']),
    };
}

export function PatchLeadRequestDtoToJSON(json: any): PatchLeadRequestDto {
    return PatchLeadRequestDtoToJSONTyped(json, false);
}

export function PatchLeadRequestDtoToJSONTyped(value?: PatchLeadRequestDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'lead': PatchLeadDtoToJSON(value['lead']),
    };
}

