/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SortingDto
 */
export interface SortingDto {
    /**
     * Order field name
     * @type {string}
     * @memberof SortingDto
     */
    orderField?: string;
    /**
     * Order direction
     * @type {string}
     * @memberof SortingDto
     */
    orderDirection?: string;
}

/**
 * Check if a given object implements the SortingDto interface.
 */
export function instanceOfSortingDto(value: object): value is SortingDto {
    return true;
}

export function SortingDtoFromJSON(json: any): SortingDto {
    return SortingDtoFromJSONTyped(json, false);
}

export function SortingDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SortingDto {
    if (json == null) {
        return json;
    }
    return {
        
        'orderField': json['orderField'] == null ? undefined : json['orderField'],
        'orderDirection': json['orderDirection'] == null ? undefined : json['orderDirection'],
    };
}

export function SortingDtoToJSON(json: any): SortingDto {
    return SortingDtoToJSONTyped(json, false);
}

export function SortingDtoToJSONTyped(value?: SortingDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'orderField': value['orderField'],
        'orderDirection': value['orderDirection'],
    };
}

