/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CreateLeadRequestDto,
  DataMetadataResponseDto,
  PatchLeadRequestDto,
} from '../models/index';
import {
    CreateLeadRequestDtoFromJSON,
    CreateLeadRequestDtoToJSON,
    DataMetadataResponseDtoFromJSON,
    DataMetadataResponseDtoToJSON,
    PatchLeadRequestDtoFromJSON,
    PatchLeadRequestDtoToJSON,
} from '../models/index';

export interface CreateLeadRequest {
    createLeadRequestDto: CreateLeadRequestDto;
}

export interface DeleteLeadRequest {
    leadId: string;
}

export interface GetLeadRequest {
    leadId: string;
}

export interface PatchLeadRequest {
    leadId: string;
    patchLeadRequestDto: PatchLeadRequestDto;
}

export interface ReplaceLeadRequest {
    leadId: string;
    createLeadRequestDto: CreateLeadRequestDto;
}

export interface SearchLeadsRequest {
    offset: number;
    limit: number;
    count?: number;
    fullName?: string;
    representsOrganization?: string;
    organizationName?: string;
    jobTitle?: string;
    statusCd?: Array<SearchLeadsStatusCdEnum>;
    sourceCd?: Array<SearchLeadsSourceCdEnum>;
    assignedTo?: string;
    companyId?: string;
    email?: string;
    phone?: string;
}

/**
 * LeadsApi - interface
 * 
 * @export
 * @interface LeadsApiInterface
 */
export interface LeadsApiInterface {
    /**
     * 
     * @summary Create a lead
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    createLeadRaw(requestParameters: CreateLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>>;

    /**
     * Create a lead
     */
    createLead(requestParameters: CreateLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object>;

    /**
     * 
     * @summary Delete a lead
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    deleteLeadRaw(requestParameters: DeleteLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Delete a lead
     */
    deleteLead(requestParameters: DeleteLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Get a lead by id
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    getLeadRaw(requestParameters: GetLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Get a lead by id
     */
    getLead(requestParameters: GetLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Patch a lead
     * @param {string} leadId 
     * @param {PatchLeadRequestDto} patchLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    patchLeadRaw(requestParameters: PatchLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Patch a lead
     */
    patchLead(requestParameters: PatchLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Patch a lead
     * @param {string} leadId 
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    replaceLeadRaw(requestParameters: ReplaceLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Patch a lead
     */
    replaceLead(requestParameters: ReplaceLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * 
     * @summary Search leads
     * @param {number} offset Pagination offset
     * @param {number} limit Pagination limit
     * @param {number} [count] Total records
     * @param {string} [fullName] Lead Full Name
     * @param {string} [representsOrganization] Represents Organization
     * @param {string} [organizationName] Lead Organization Name
     * @param {string} [jobTitle] Lead Job Title
     * @param {Array<'pvx:NEW' | 'pvx:ENGAGED' | 'pvx:QUALIFIED' | 'pvx:IN_PROGRESS' | 'pvx:NOT_QUALIFIED' | 'pvx:LOST' | 'pvx:NOT_INTERESTED'>} [statusCd] Lead Status Code
     * @param {Array<'pvx:NEW' | 'pvx:ENGAGED' | 'pvx:QUALIFIED' | 'pvx:IN_PROGRESS' | 'pvx:NOT_QUALIFIED' | 'pvx:LOST' | 'pvx:NOT_INTERESTED'>} [sourceCd] Lead Source Code
     * @param {string} [assignedTo] Assigned To
     * @param {string} [companyId] Company Id
     * @param {string} [email] Lead Email
     * @param {string} [phone] Lead Phone
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    searchLeadsRaw(requestParameters: SearchLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataMetadataResponseDto>>;

    /**
     * Search leads
     */
    searchLeads(requestParameters: SearchLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataMetadataResponseDto>;

}

/**
 * 
 */
export class LeadsApi extends runtime.BaseAPI implements LeadsApiInterface {

    /**
     * Create a lead
     */
    async createLeadRaw(requestParameters: CreateLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<object>> {
        if (requestParameters['createLeadRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createLeadRequestDto',
                'Required parameter "createLeadRequestDto" was null or undefined when calling createLead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/system/leads`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLeadRequestDtoToJSON(requestParameters['createLeadRequestDto']),
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     * Create a lead
     */
    async createLead(requestParameters: CreateLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<object> {
        const response = await this.createLeadRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Delete a lead
     */
    async deleteLeadRaw(requestParameters: DeleteLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['leadId'] == null) {
            throw new runtime.RequiredError(
                'leadId',
                'Required parameter "leadId" was null or undefined when calling deleteLead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/system/leads/{leadId}`.replace(`{${"leadId"}}`, encodeURIComponent(String(requestParameters['leadId']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Delete a lead
     */
    async deleteLead(requestParameters: DeleteLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteLeadRaw(requestParameters, initOverrides);
    }

    /**
     * Get a lead by id
     */
    async getLeadRaw(requestParameters: GetLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['leadId'] == null) {
            throw new runtime.RequiredError(
                'leadId',
                'Required parameter "leadId" was null or undefined when calling getLead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/system/leads/{leadId}`.replace(`{${"leadId"}}`, encodeURIComponent(String(requestParameters['leadId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Get a lead by id
     */
    async getLead(requestParameters: GetLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.getLeadRaw(requestParameters, initOverrides);
    }

    /**
     * Patch a lead
     */
    async patchLeadRaw(requestParameters: PatchLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['leadId'] == null) {
            throw new runtime.RequiredError(
                'leadId',
                'Required parameter "leadId" was null or undefined when calling patchLead().'
            );
        }

        if (requestParameters['patchLeadRequestDto'] == null) {
            throw new runtime.RequiredError(
                'patchLeadRequestDto',
                'Required parameter "patchLeadRequestDto" was null or undefined when calling patchLead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/system/leads/{leadId}`.replace(`{${"leadId"}}`, encodeURIComponent(String(requestParameters['leadId']))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PatchLeadRequestDtoToJSON(requestParameters['patchLeadRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Patch a lead
     */
    async patchLead(requestParameters: PatchLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.patchLeadRaw(requestParameters, initOverrides);
    }

    /**
     * Patch a lead
     */
    async replaceLeadRaw(requestParameters: ReplaceLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['leadId'] == null) {
            throw new runtime.RequiredError(
                'leadId',
                'Required parameter "leadId" was null or undefined when calling replaceLead().'
            );
        }

        if (requestParameters['createLeadRequestDto'] == null) {
            throw new runtime.RequiredError(
                'createLeadRequestDto',
                'Required parameter "createLeadRequestDto" was null or undefined when calling replaceLead().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/system/leads/{leadId}`.replace(`{${"leadId"}}`, encodeURIComponent(String(requestParameters['leadId']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CreateLeadRequestDtoToJSON(requestParameters['createLeadRequestDto']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Patch a lead
     */
    async replaceLead(requestParameters: ReplaceLeadRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.replaceLeadRaw(requestParameters, initOverrides);
    }

    /**
     * Search leads
     */
    async searchLeadsRaw(requestParameters: SearchLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataMetadataResponseDto>> {
        if (requestParameters['offset'] == null) {
            throw new runtime.RequiredError(
                'offset',
                'Required parameter "offset" was null or undefined when calling searchLeads().'
            );
        }

        if (requestParameters['limit'] == null) {
            throw new runtime.RequiredError(
                'limit',
                'Required parameter "limit" was null or undefined when calling searchLeads().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['offset'] != null) {
            queryParameters['offset'] = requestParameters['offset'];
        }

        if (requestParameters['limit'] != null) {
            queryParameters['limit'] = requestParameters['limit'];
        }

        if (requestParameters['count'] != null) {
            queryParameters['count'] = requestParameters['count'];
        }

        if (requestParameters['fullName'] != null) {
            queryParameters['fullName'] = requestParameters['fullName'];
        }

        if (requestParameters['representsOrganization'] != null) {
            queryParameters['representsOrganization'] = requestParameters['representsOrganization'];
        }

        if (requestParameters['organizationName'] != null) {
            queryParameters['organizationName'] = requestParameters['organizationName'];
        }

        if (requestParameters['jobTitle'] != null) {
            queryParameters['jobTitle'] = requestParameters['jobTitle'];
        }

        if (requestParameters['statusCd'] != null) {
            queryParameters['statusCd'] = requestParameters['statusCd'];
        }

        if (requestParameters['sourceCd'] != null) {
            queryParameters['sourceCd'] = requestParameters['sourceCd'];
        }

        if (requestParameters['assignedTo'] != null) {
            queryParameters['assignedTo'] = requestParameters['assignedTo'];
        }

        if (requestParameters['companyId'] != null) {
            queryParameters['companyId'] = requestParameters['companyId'];
        }

        if (requestParameters['email'] != null) {
            queryParameters['email'] = requestParameters['email'];
        }

        if (requestParameters['phone'] != null) {
            queryParameters['phone'] = requestParameters['phone'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/system/leads`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataMetadataResponseDtoFromJSON(jsonValue));
    }

    /**
     * Search leads
     */
    async searchLeads(requestParameters: SearchLeadsRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataMetadataResponseDto> {
        const response = await this.searchLeadsRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const SearchLeadsStatusCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;
export type SearchLeadsStatusCdEnum = typeof SearchLeadsStatusCdEnum[keyof typeof SearchLeadsStatusCdEnum];
/**
 * @export
 */
export const SearchLeadsSourceCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;
export type SearchLeadsSourceCdEnum = typeof SearchLeadsSourceCdEnum[keyof typeof SearchLeadsSourceCdEnum];
