/* tslint:disable */
/* eslint-disable */
/**
 * Leads API
 * Leads related operations api
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from './configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ContactInfoDto
 */
export interface ContactInfoDto {
    /**
     * ContactInfo Id
     * @type {string}
     * @memberof ContactInfoDto
     */
    'id': string;
    /**
     * ContactInfo Type
     * @type {string}
     * @memberof ContactInfoDto
     */
    'typeCd': ContactInfoDtoTypeCdEnum;
    /**
     * ContactInfo Value
     * @type {string}
     * @memberof ContactInfoDto
     */
    'value': string;
    /**
     * Is Primary ContactInfo
     * @type {boolean}
     * @memberof ContactInfoDto
     */
    'isPrimary': boolean;
    /**
     * Created DateTime
     * @type {string}
     * @memberof ContactInfoDto
     */
    'createdAt': string;
}

export const ContactInfoDtoTypeCdEnum = {
    Email: 'email',
    Phone: 'phone'
} as const;

export type ContactInfoDtoTypeCdEnum = typeof ContactInfoDtoTypeCdEnum[keyof typeof ContactInfoDtoTypeCdEnum];

/**
 * 
 * @export
 * @interface CreateContactInfoDto
 */
export interface CreateContactInfoDto {
    /**
     * ContactInfo Type
     * @type {string}
     * @memberof CreateContactInfoDto
     */
    'typeCd': CreateContactInfoDtoTypeCdEnum;
    /**
     * ContactInfo Value
     * @type {string}
     * @memberof CreateContactInfoDto
     */
    'value': string;
    /**
     * Is Primary ContactInfo
     * @type {boolean}
     * @memberof CreateContactInfoDto
     */
    'isPrimary': boolean;
}

export const CreateContactInfoDtoTypeCdEnum = {
    Email: 'email',
    Phone: 'phone'
} as const;

export type CreateContactInfoDtoTypeCdEnum = typeof CreateContactInfoDtoTypeCdEnum[keyof typeof CreateContactInfoDtoTypeCdEnum];

/**
 * 
 * @export
 * @interface CreateLead201Response
 */
export interface CreateLead201Response {
    /**
     * 
     * @type {CreateUpdateLeadResponseDto}
     * @memberof CreateLead201Response
     */
    'data': CreateUpdateLeadResponseDto;
}
/**
 * 
 * @export
 * @interface CreateLeadDto
 */
export interface CreateLeadDto {
    /**
     * Lead First Name
     * @type {string}
     * @memberof CreateLeadDto
     */
    'firstName': string;
    /**
     * Lead Second Name
     * @type {string}
     * @memberof CreateLeadDto
     */
    'secondName'?: string;
    /**
     * Lead Last Name
     * @type {string}
     * @memberof CreateLeadDto
     */
    'lastName': string;
    /**
     * Lead Second Last Name
     * @type {string}
     * @memberof CreateLeadDto
     */
    'secondLastName'?: string;
    /**
     * Represents Organization
     * @type {boolean}
     * @memberof CreateLeadDto
     */
    'representsOrganization': boolean;
    /**
     * Lead Organization Name
     * @type {string}
     * @memberof CreateLeadDto
     */
    'organizationName'?: string;
    /**
     * Lead Job Title
     * @type {string}
     * @memberof CreateLeadDto
     */
    'jobTitle'?: string;
    /**
     * Lead Contact Information
     * @type {Array<CreateContactInfoDto>}
     * @memberof CreateLeadDto
     */
    'contactData': Array<CreateContactInfoDto>;
    /**
     * Lead Source Code
     * @type {string}
     * @memberof CreateLeadDto
     */
    'sourceCd': CreateLeadDtoSourceCdEnum;
    /**
     * Assigned To
     * @type {string}
     * @memberof CreateLeadDto
     */
    'assignedTo'?: string;
    /**
     * Assigned DateTime
     * @type {string}
     * @memberof CreateLeadDto
     */
    'assignedAt'?: string;
    /**
     * Company Id
     * @type {string}
     * @memberof CreateLeadDto
     */
    'companyId': string;
}

export const CreateLeadDtoSourceCdEnum = {
    Marketplace: 'marketplace',
    Website: 'website',
    Email: 'email',
    Phone: 'phone',
    Facebook: 'facebook',
    Instagram: 'instagram',
    Twitter: 'twitter',
    Linkedin: 'linkedin',
    Youtube: 'youtube',
    Google: 'google',
    Other: 'other'
} as const;

export type CreateLeadDtoSourceCdEnum = typeof CreateLeadDtoSourceCdEnum[keyof typeof CreateLeadDtoSourceCdEnum];

/**
 * 
 * @export
 * @interface CreateLeadRequestDto
 */
export interface CreateLeadRequestDto {
    /**
     * Lead
     * @type {CreateLeadDto}
     * @memberof CreateLeadRequestDto
     */
    'lead': CreateLeadDto;
}
/**
 * 
 * @export
 * @interface CreateUpdateLeadResponseDto
 */
export interface CreateUpdateLeadResponseDto {
    /**
     * Lead
     * @type {LeadDto}
     * @memberof CreateUpdateLeadResponseDto
     */
    'lead': LeadDto;
}
/**
 * 
 * @export
 * @interface DataMetadataResponseDto
 */
export interface DataMetadataResponseDto {
    /**
     * Data info
     * @type {object}
     * @memberof DataMetadataResponseDto
     */
    'data': object;
    /**
     * Metadata info
     * @type {MetadataResponseDto}
     * @memberof DataMetadataResponseDto
     */
    'metadata': MetadataResponseDto;
}
/**
 * 
 * @export
 * @interface DataResponseDto
 */
export interface DataResponseDto {
    /**
     * Data info
     * @type {object}
     * @memberof DataResponseDto
     */
    'data': object;
}
/**
 * 
 * @export
 * @interface GetLead200Response
 */
export interface GetLead200Response {
    /**
     * 
     * @type {LeadDto}
     * @memberof GetLead200Response
     */
    'data': LeadDto;
}
/**
 * 
 * @export
 * @interface LeadDto
 */
export interface LeadDto {
    /**
     * Entity Id
     * @type {string}
     * @memberof LeadDto
     */
    'id': string;
    /**
     * Created DateTime
     * @type {string}
     * @memberof LeadDto
     */
    'createdAt': string;
    /**
     * Updated DateTime
     * @type {string}
     * @memberof LeadDto
     */
    'updatedAt': string;
    /**
     * Deleted DateTime
     * @type {string}
     * @memberof LeadDto
     */
    'deletedAt': string;
    /**
     * Lead First Name
     * @type {string}
     * @memberof LeadDto
     */
    'firstName': string;
    /**
     * Lead Second Name
     * @type {string}
     * @memberof LeadDto
     */
    'secondName'?: string;
    /**
     * Lead Last Name
     * @type {string}
     * @memberof LeadDto
     */
    'lastName': string;
    /**
     * Lead Second Last Name
     * @type {string}
     * @memberof LeadDto
     */
    'secondLastName'?: string;
    /**
     * Lead Full Name
     * @type {string}
     * @memberof LeadDto
     */
    'fullName': string;
    /**
     * Represents Organization
     * @type {boolean}
     * @memberof LeadDto
     */
    'representsOrganization': boolean;
    /**
     * Lead Organization Name
     * @type {string}
     * @memberof LeadDto
     */
    'organizationName'?: string;
    /**
     * Lead Job Title
     * @type {string}
     * @memberof LeadDto
     */
    'jobTitle'?: string;
    /**
     * Lead Contact Information
     * @type {Array<ContactInfoDto>}
     * @memberof LeadDto
     */
    'contactData': Array<ContactInfoDto>;
    /**
     * Lead Status Code
     * @type {string}
     * @memberof LeadDto
     */
    'statusCd': LeadDtoStatusCdEnum;
    /**
     * Lead Source Code
     * @type {string}
     * @memberof LeadDto
     */
    'sourceCd': LeadDtoSourceCdEnum;
    /**
     * Assigned To
     * @type {string}
     * @memberof LeadDto
     */
    'assignedTo'?: string;
    /**
     * Assigned DateTime
     * @type {string}
     * @memberof LeadDto
     */
    'assignedAt'?: string;
    /**
     * Company Id
     * @type {string}
     * @memberof LeadDto
     */
    'companyId': string;
}

export const LeadDtoStatusCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;

export type LeadDtoStatusCdEnum = typeof LeadDtoStatusCdEnum[keyof typeof LeadDtoStatusCdEnum];
export const LeadDtoSourceCdEnum = {
    Marketplace: 'marketplace',
    Website: 'website',
    Email: 'email',
    Phone: 'phone',
    Facebook: 'facebook',
    Instagram: 'instagram',
    Twitter: 'twitter',
    Linkedin: 'linkedin',
    Youtube: 'youtube',
    Google: 'google',
    Other: 'other'
} as const;

export type LeadDtoSourceCdEnum = typeof LeadDtoSourceCdEnum[keyof typeof LeadDtoSourceCdEnum];

/**
 * 
 * @export
 * @interface MetadataResponseDto
 */
export interface MetadataResponseDto {
    /**
     * Offset pagination info
     * @type {OffsetPaginationDto}
     * @memberof MetadataResponseDto
     */
    'pagination'?: OffsetPaginationDto;
    /**
     * Sorting info
     * @type {SortingDto}
     * @memberof MetadataResponseDto
     */
    'sort'?: SortingDto;
    /**
     * Filter info
     * @type {object}
     * @memberof MetadataResponseDto
     */
    'filter'?: object;
    /**
     * Projection fields
     * @type {Array<string>}
     * @memberof MetadataResponseDto
     */
    'projection'?: Array<string>;
}
/**
 * 
 * @export
 * @interface OffsetPaginationDto
 */
export interface OffsetPaginationDto {
    /**
     * Pagination offset
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    'offset': number;
    /**
     * Pagination limit
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    'limit': number;
    /**
     * Total records
     * @type {number}
     * @memberof OffsetPaginationDto
     */
    'count'?: number;
}
/**
 * 
 * @export
 * @interface PatchLeadDto
 */
export interface PatchLeadDto {
    /**
     * Lead First Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    'firstName': string;
    /**
     * Lead Second Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    'secondName'?: string;
    /**
     * Lead Last Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    'lastName': string;
    /**
     * Lead Second Last Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    'secondLastName'?: string;
    /**
     * Represents Organization
     * @type {boolean}
     * @memberof PatchLeadDto
     */
    'representsOrganization': boolean;
    /**
     * Lead Organization Name
     * @type {string}
     * @memberof PatchLeadDto
     */
    'organizationName'?: string;
    /**
     * Lead Job Title
     * @type {string}
     * @memberof PatchLeadDto
     */
    'jobTitle'?: string;
    /**
     * Lead Contact Information
     * @type {Array<CreateContactInfoDto>}
     * @memberof PatchLeadDto
     */
    'contactData': Array<CreateContactInfoDto>;
    /**
     * Lead Source Code
     * @type {string}
     * @memberof PatchLeadDto
     */
    'sourceCd': PatchLeadDtoSourceCdEnum;
    /**
     * Assigned To
     * @type {string}
     * @memberof PatchLeadDto
     */
    'assignedTo'?: string;
    /**
     * Assigned DateTime
     * @type {string}
     * @memberof PatchLeadDto
     */
    'assignedAt'?: string;
    /**
     * Company Id
     * @type {string}
     * @memberof PatchLeadDto
     */
    'companyId': string;
}

export const PatchLeadDtoSourceCdEnum = {
    Marketplace: 'marketplace',
    Website: 'website',
    Email: 'email',
    Phone: 'phone',
    Facebook: 'facebook',
    Instagram: 'instagram',
    Twitter: 'twitter',
    Linkedin: 'linkedin',
    Youtube: 'youtube',
    Google: 'google',
    Other: 'other'
} as const;

export type PatchLeadDtoSourceCdEnum = typeof PatchLeadDtoSourceCdEnum[keyof typeof PatchLeadDtoSourceCdEnum];

/**
 * 
 * @export
 * @interface PatchLeadRequestDto
 */
export interface PatchLeadRequestDto {
    /**
     * Lead
     * @type {PatchLeadDto}
     * @memberof PatchLeadRequestDto
     */
    'lead': PatchLeadDto;
}
/**
 * 
 * @export
 * @interface SearchLeadRequestDto
 */
export interface SearchLeadRequestDto {
    /**
     * Pagination offset
     * @type {number}
     * @memberof SearchLeadRequestDto
     */
    'offset': number;
    /**
     * Pagination limit
     * @type {number}
     * @memberof SearchLeadRequestDto
     */
    'limit': number;
    /**
     * Total records
     * @type {number}
     * @memberof SearchLeadRequestDto
     */
    'count'?: number;
    /**
     * Lead Full Name
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'fullName'?: string;
    /**
     * Represents Organization
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'representsOrganization'?: string;
    /**
     * Lead Organization Name
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'organizationName'?: string;
    /**
     * Lead Job Title
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'jobTitle'?: string;
    /**
     * Lead Status Code
     * @type {Array<string>}
     * @memberof SearchLeadRequestDto
     */
    'statusCd'?: Array<SearchLeadRequestDtoStatusCdEnum>;
    /**
     * Lead Source Code
     * @type {Array<string>}
     * @memberof SearchLeadRequestDto
     */
    'sourceCd'?: Array<SearchLeadRequestDtoSourceCdEnum>;
    /**
     * Assigned To
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'assignedTo'?: string;
    /**
     * Company Id
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'companyId'?: string;
    /**
     * Lead Email
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'email'?: string;
    /**
     * Lead Phone
     * @type {string}
     * @memberof SearchLeadRequestDto
     */
    'phone'?: string;
}

export const SearchLeadRequestDtoStatusCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;

export type SearchLeadRequestDtoStatusCdEnum = typeof SearchLeadRequestDtoStatusCdEnum[keyof typeof SearchLeadRequestDtoStatusCdEnum];
export const SearchLeadRequestDtoSourceCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;

export type SearchLeadRequestDtoSourceCdEnum = typeof SearchLeadRequestDtoSourceCdEnum[keyof typeof SearchLeadRequestDtoSourceCdEnum];

/**
 * 
 * @export
 * @interface SearchLeads200Response
 */
export interface SearchLeads200Response {
    /**
     * 
     * @type {Array<LeadDto>}
     * @memberof SearchLeads200Response
     */
    'data': Array<LeadDto>;
    /**
     * 
     * @type {SearchLeads200ResponseMetadata}
     * @memberof SearchLeads200Response
     */
    'metadata': SearchLeads200ResponseMetadata;
}
/**
 * 
 * @export
 * @interface SearchLeads200ResponseMetadata
 */
export interface SearchLeads200ResponseMetadata {
    /**
     * 
     * @type {OffsetPaginationDto}
     * @memberof SearchLeads200ResponseMetadata
     */
    'pagination'?: OffsetPaginationDto;
    /**
     * 
     * @type {SortingDto}
     * @memberof SearchLeads200ResponseMetadata
     */
    'sort'?: SortingDto;
    /**
     * 
     * @type {SearchLeadRequestDto}
     * @memberof SearchLeads200ResponseMetadata
     */
    'filter'?: SearchLeadRequestDto;
    /**
     * 
     * @type {Array<string>}
     * @memberof SearchLeads200ResponseMetadata
     */
    'projection'?: Array<string>;
}
/**
 * 
 * @export
 * @interface SortingDto
 */
export interface SortingDto {
    /**
     * Order field name
     * @type {string}
     * @memberof SortingDto
     */
    'orderField'?: string;
    /**
     * Order direction
     * @type {string}
     * @memberof SortingDto
     */
    'orderDirection'?: string;
}

/**
 * HealthApi - axios parameter creator
 * @export
 */
export const HealthApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/health-check`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * HealthApi - functional programming interface
 * @export
 */
export const HealthApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = HealthApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async healthCheck(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.healthCheck(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['HealthApi.healthCheck']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * HealthApi - factory interface
 * @export
 */
export const HealthApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = HealthApiFp(configuration)
    return {
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.healthCheck(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * HealthApi - interface
 * @export
 * @interface HealthApi
 */
export interface HealthApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApiInterface
     */
    healthCheck(options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * HealthApi - object-oriented interface
 * @export
 * @class HealthApi
 * @extends {BaseAPI}
 */
export class HealthApi extends BaseAPI implements HealthApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof HealthApi
     */
    public healthCheck(options?: RawAxiosRequestConfig) {
        return HealthApiFp(this.configuration).healthCheck(options).then((request) => request(this.axios, this.basePath));
    }
}



/**
 * LeadsApi - axios parameter creator
 * @export
 */
export const LeadsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Create a lead
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLead: async (createLeadRequestDto: CreateLeadRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createLeadRequestDto' is not null or undefined
            assertParamExists('createLead', 'createLeadRequestDto', createLeadRequestDto)
            const localVarPath = `/api/system/leads`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLeadRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete a lead
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLead: async (leadId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leadId' is not null or undefined
            assertParamExists('deleteLead', 'leadId', leadId)
            const localVarPath = `/api/system/leads/{leadId}`
                .replace(`{${"leadId"}}`, encodeURIComponent(String(leadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get a lead by id
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLead: async (leadId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leadId' is not null or undefined
            assertParamExists('getLead', 'leadId', leadId)
            const localVarPath = `/api/system/leads/{leadId}`
                .replace(`{${"leadId"}}`, encodeURIComponent(String(leadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Patch a lead
         * @param {string} leadId 
         * @param {PatchLeadRequestDto} patchLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchLead: async (leadId: string, patchLeadRequestDto: PatchLeadRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leadId' is not null or undefined
            assertParamExists('patchLead', 'leadId', leadId)
            // verify required parameter 'patchLeadRequestDto' is not null or undefined
            assertParamExists('patchLead', 'patchLeadRequestDto', patchLeadRequestDto)
            const localVarPath = `/api/system/leads/{leadId}`
                .replace(`{${"leadId"}}`, encodeURIComponent(String(leadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(patchLeadRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Replace a lead
         * @param {string} leadId 
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceLead: async (leadId: string, createLeadRequestDto: CreateLeadRequestDto, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'leadId' is not null or undefined
            assertParamExists('replaceLead', 'leadId', leadId)
            // verify required parameter 'createLeadRequestDto' is not null or undefined
            assertParamExists('replaceLead', 'createLeadRequestDto', createLeadRequestDto)
            const localVarPath = `/api/system/leads/{leadId}`
                .replace(`{${"leadId"}}`, encodeURIComponent(String(leadId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createLeadRequestDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Search leads
         * @param {number} offset Pagination offset
         * @param {number} limit Pagination limit
         * @param {number} [count] Total records
         * @param {string} [fullName] Lead Full Name
         * @param {string} [representsOrganization] Represents Organization
         * @param {string} [organizationName] Lead Organization Name
         * @param {string} [jobTitle] Lead Job Title
         * @param {Array<SearchLeadsStatusCdEnum>} [statusCd] Lead Status Code
         * @param {Array<SearchLeadsSourceCdEnum>} [sourceCd] Lead Source Code
         * @param {string} [assignedTo] Assigned To
         * @param {string} [companyId] Company Id
         * @param {string} [email] Lead Email
         * @param {string} [phone] Lead Phone
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchLeads: async (offset: number, limit: number, count?: number, fullName?: string, representsOrganization?: string, organizationName?: string, jobTitle?: string, statusCd?: Array<SearchLeadsStatusCdEnum>, sourceCd?: Array<SearchLeadsSourceCdEnum>, assignedTo?: string, companyId?: string, email?: string, phone?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'offset' is not null or undefined
            assertParamExists('searchLeads', 'offset', offset)
            // verify required parameter 'limit' is not null or undefined
            assertParamExists('searchLeads', 'limit', limit)
            const localVarPath = `/api/system/leads`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (fullName !== undefined) {
                localVarQueryParameter['fullName'] = fullName;
            }

            if (representsOrganization !== undefined) {
                localVarQueryParameter['representsOrganization'] = representsOrganization;
            }

            if (organizationName !== undefined) {
                localVarQueryParameter['organizationName'] = organizationName;
            }

            if (jobTitle !== undefined) {
                localVarQueryParameter['jobTitle'] = jobTitle;
            }

            if (statusCd) {
                localVarQueryParameter['statusCd'] = statusCd;
            }

            if (sourceCd) {
                localVarQueryParameter['sourceCd'] = sourceCd;
            }

            if (assignedTo !== undefined) {
                localVarQueryParameter['assignedTo'] = assignedTo;
            }

            if (companyId !== undefined) {
                localVarQueryParameter['companyId'] = companyId;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            if (phone !== undefined) {
                localVarQueryParameter['phone'] = phone;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * LeadsApi - functional programming interface
 * @export
 */
export const LeadsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = LeadsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Create a lead
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createLead(createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateLead201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createLead(createLeadRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.createLead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Delete a lead
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteLead(leadId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteLead(leadId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.deleteLead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get a lead by id
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getLead(leadId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<GetLead200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getLead(leadId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.getLead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Patch a lead
         * @param {string} leadId 
         * @param {PatchLeadRequestDto} patchLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async patchLead(leadId: string, patchLeadRequestDto: PatchLeadRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateLead201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchLead(leadId, patchLeadRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.patchLead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Replace a lead
         * @param {string} leadId 
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async replaceLead(leadId: string, createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateLead201Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.replaceLead(leadId, createLeadRequestDto, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.replaceLead']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Search leads
         * @param {number} offset Pagination offset
         * @param {number} limit Pagination limit
         * @param {number} [count] Total records
         * @param {string} [fullName] Lead Full Name
         * @param {string} [representsOrganization] Represents Organization
         * @param {string} [organizationName] Lead Organization Name
         * @param {string} [jobTitle] Lead Job Title
         * @param {Array<SearchLeadsStatusCdEnum>} [statusCd] Lead Status Code
         * @param {Array<SearchLeadsSourceCdEnum>} [sourceCd] Lead Source Code
         * @param {string} [assignedTo] Assigned To
         * @param {string} [companyId] Company Id
         * @param {string} [email] Lead Email
         * @param {string} [phone] Lead Phone
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async searchLeads(offset: number, limit: number, count?: number, fullName?: string, representsOrganization?: string, organizationName?: string, jobTitle?: string, statusCd?: Array<SearchLeadsStatusCdEnum>, sourceCd?: Array<SearchLeadsSourceCdEnum>, assignedTo?: string, companyId?: string, email?: string, phone?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SearchLeads200Response>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.searchLeads(offset, limit, count, fullName, representsOrganization, organizationName, jobTitle, statusCd, sourceCd, assignedTo, companyId, email, phone, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['LeadsApi.searchLeads']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * LeadsApi - factory interface
 * @export
 */
export const LeadsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = LeadsApiFp(configuration)
    return {
        /**
         * 
         * @summary Create a lead
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createLead(createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response> {
            return localVarFp.createLead(createLeadRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete a lead
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteLead(leadId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteLead(leadId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get a lead by id
         * @param {string} leadId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getLead(leadId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetLead200Response> {
            return localVarFp.getLead(leadId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Patch a lead
         * @param {string} leadId 
         * @param {PatchLeadRequestDto} patchLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        patchLead(leadId: string, patchLeadRequestDto: PatchLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response> {
            return localVarFp.patchLead(leadId, patchLeadRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Replace a lead
         * @param {string} leadId 
         * @param {CreateLeadRequestDto} createLeadRequestDto 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        replaceLead(leadId: string, createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response> {
            return localVarFp.replaceLead(leadId, createLeadRequestDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Search leads
         * @param {number} offset Pagination offset
         * @param {number} limit Pagination limit
         * @param {number} [count] Total records
         * @param {string} [fullName] Lead Full Name
         * @param {string} [representsOrganization] Represents Organization
         * @param {string} [organizationName] Lead Organization Name
         * @param {string} [jobTitle] Lead Job Title
         * @param {Array<SearchLeadsStatusCdEnum>} [statusCd] Lead Status Code
         * @param {Array<SearchLeadsSourceCdEnum>} [sourceCd] Lead Source Code
         * @param {string} [assignedTo] Assigned To
         * @param {string} [companyId] Company Id
         * @param {string} [email] Lead Email
         * @param {string} [phone] Lead Phone
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        searchLeads(offset: number, limit: number, count?: number, fullName?: string, representsOrganization?: string, organizationName?: string, jobTitle?: string, statusCd?: Array<SearchLeadsStatusCdEnum>, sourceCd?: Array<SearchLeadsSourceCdEnum>, assignedTo?: string, companyId?: string, email?: string, phone?: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchLeads200Response> {
            return localVarFp.searchLeads(offset, limit, count, fullName, representsOrganization, organizationName, jobTitle, statusCd, sourceCd, assignedTo, companyId, email, phone, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * LeadsApi - interface
 * @export
 * @interface LeadsApi
 */
export interface LeadsApiInterface {
    /**
     * 
     * @summary Create a lead
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    createLead(createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response>;

    /**
     * 
     * @summary Delete a lead
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    deleteLead(leadId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Get a lead by id
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    getLead(leadId: string, options?: RawAxiosRequestConfig): AxiosPromise<GetLead200Response>;

    /**
     * 
     * @summary Patch a lead
     * @param {string} leadId 
     * @param {PatchLeadRequestDto} patchLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    patchLead(leadId: string, patchLeadRequestDto: PatchLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response>;

    /**
     * 
     * @summary Replace a lead
     * @param {string} leadId 
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    replaceLead(leadId: string, createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig): AxiosPromise<CreateLead201Response>;

    /**
     * 
     * @summary Search leads
     * @param {number} offset Pagination offset
     * @param {number} limit Pagination limit
     * @param {number} [count] Total records
     * @param {string} [fullName] Lead Full Name
     * @param {string} [representsOrganization] Represents Organization
     * @param {string} [organizationName] Lead Organization Name
     * @param {string} [jobTitle] Lead Job Title
     * @param {Array<SearchLeadsStatusCdEnum>} [statusCd] Lead Status Code
     * @param {Array<SearchLeadsSourceCdEnum>} [sourceCd] Lead Source Code
     * @param {string} [assignedTo] Assigned To
     * @param {string} [companyId] Company Id
     * @param {string} [email] Lead Email
     * @param {string} [phone] Lead Phone
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApiInterface
     */
    searchLeads(offset: number, limit: number, count?: number, fullName?: string, representsOrganization?: string, organizationName?: string, jobTitle?: string, statusCd?: Array<SearchLeadsStatusCdEnum>, sourceCd?: Array<SearchLeadsSourceCdEnum>, assignedTo?: string, companyId?: string, email?: string, phone?: string, options?: RawAxiosRequestConfig): AxiosPromise<SearchLeads200Response>;

}

/**
 * LeadsApi - object-oriented interface
 * @export
 * @class LeadsApi
 * @extends {BaseAPI}
 */
export class LeadsApi extends BaseAPI implements LeadsApiInterface {
    /**
     * 
     * @summary Create a lead
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public createLead(createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).createLead(createLeadRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete a lead
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public deleteLead(leadId: string, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).deleteLead(leadId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get a lead by id
     * @param {string} leadId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public getLead(leadId: string, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).getLead(leadId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Patch a lead
     * @param {string} leadId 
     * @param {PatchLeadRequestDto} patchLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public patchLead(leadId: string, patchLeadRequestDto: PatchLeadRequestDto, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).patchLead(leadId, patchLeadRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Replace a lead
     * @param {string} leadId 
     * @param {CreateLeadRequestDto} createLeadRequestDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public replaceLead(leadId: string, createLeadRequestDto: CreateLeadRequestDto, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).replaceLead(leadId, createLeadRequestDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Search leads
     * @param {number} offset Pagination offset
     * @param {number} limit Pagination limit
     * @param {number} [count] Total records
     * @param {string} [fullName] Lead Full Name
     * @param {string} [representsOrganization] Represents Organization
     * @param {string} [organizationName] Lead Organization Name
     * @param {string} [jobTitle] Lead Job Title
     * @param {Array<SearchLeadsStatusCdEnum>} [statusCd] Lead Status Code
     * @param {Array<SearchLeadsSourceCdEnum>} [sourceCd] Lead Source Code
     * @param {string} [assignedTo] Assigned To
     * @param {string} [companyId] Company Id
     * @param {string} [email] Lead Email
     * @param {string} [phone] Lead Phone
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof LeadsApi
     */
    public searchLeads(offset: number, limit: number, count?: number, fullName?: string, representsOrganization?: string, organizationName?: string, jobTitle?: string, statusCd?: Array<SearchLeadsStatusCdEnum>, sourceCd?: Array<SearchLeadsSourceCdEnum>, assignedTo?: string, companyId?: string, email?: string, phone?: string, options?: RawAxiosRequestConfig) {
        return LeadsApiFp(this.configuration).searchLeads(offset, limit, count, fullName, representsOrganization, organizationName, jobTitle, statusCd, sourceCd, assignedTo, companyId, email, phone, options).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const SearchLeadsStatusCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;
export type SearchLeadsStatusCdEnum = typeof SearchLeadsStatusCdEnum[keyof typeof SearchLeadsStatusCdEnum];
/**
 * @export
 */
export const SearchLeadsSourceCdEnum = {
    PvxNew: 'pvx:NEW',
    PvxEngaged: 'pvx:ENGAGED',
    PvxQualified: 'pvx:QUALIFIED',
    PvxInProgress: 'pvx:IN_PROGRESS',
    PvxNotQualified: 'pvx:NOT_QUALIFIED',
    PvxLost: 'pvx:LOST',
    PvxNotInterested: 'pvx:NOT_INTERESTED'
} as const;
export type SearchLeadsSourceCdEnum = typeof SearchLeadsSourceCdEnum[keyof typeof SearchLeadsSourceCdEnum];


